[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_lines = [
	"pragma: no cover",
	"raise NotImplementedError",
	"if __name__ == .__main__.:",
	"if typing.TYPE_CHECKING:",
]

[tool.mypy]
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
strict_equality = true

[[tool.mypy.overrides]]
module = "phoenix6.*"
# https://github.com/CrossTheRoadElec/Phoenix-Releases/issues/61#issuecomment-1890171743
ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = '.'

[tool.ruff]
select = ["E", "F", "B", "UP", "C4", "SIM"]
ignore = ["E501"]
target-version = "py39"

[tool.pdm]
package-type = "application"

[tool.pdm.scripts]
deploy = "robotpy deploy"
download = "robotpy sync --no-install"
sim = "robotpy sim"
test = "robotpy test"

[tool.pdm.dev-dependencies]
dev = [
	"hypothesis",
	"pytest>=7.2.0",
]

[project]
name = "pycrescendo"
version = "0.0.0"
description = "The Drop Bears' FRC 2024 robot code"
authors = [
	{name = "The Drop Bears", email = "enquiries@thedropbears.org.au"},
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.10,<3.13"

dependencies = [
	"numpy~=1.25",
	"phoenix6==24.1.0",
	# robotpy[apriltag] pins numpy to a version that doesn't build cleanly on Python 3.12.
	"robotpy==2024.1.1.1",
	"robotpy-apriltag==2024.1.1.1",
	"robotpy-ctre==2024.1.0",
	"robotpy-navx==2024.1.0",
	"robotpy-rev==2024.2.0",
	"robotpy-wpilib-utilities==2024.0.0",
]

[tool.robotpy]
requires = [
	"numpy~=1.25",
	"phoenix6==24.1.0",
	"robotpy-ctre==2024.1.0",
	"robotpy-navx==2024.1.0",
	"robotpy-rev==2024.2.0",
	"robotpy-wpilib-utilities==2024.0.0",
]
robotpy_version = "2024.1.1.1"
robotpy_extras = ["apriltag"]
