[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_lines = [
	"pragma: no cover",
	"raise NotImplementedError",
	"if __name__ == .__main__.:",
	"if typing.TYPE_CHECKING:",
]

[tool.mypy]
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
strict_equality = true

[[tool.mypy.overrides]]
module = "phoenix6.*"
# https://github.com/CrossTheRoadElec/Phoenix-Releases/issues/61#issuecomment-1890171743
ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = '.'

[tool.ruff]
select = ["E", "F", "B", "UP", "C4", "SIM"]
ignore = ["E501"]
target-version = "py39"

[tool.robotpy]
requires = [
	"numpy~=1.25.2",
	"phoenix6==24.1.0",
	"robotpy-ctre==2024.1.0",
	"robotpy-navx==2024.1.0",
	"robotpy-rev==2024.2.0",
	"robotpy-wpilib-utilities==2024.0.0",
]
robotpy_version = "2024.1.1.1"
robotpy_extras = ["apriltag"]
